import boto3
import os
import json
from concurrent.futures import ThreadPoolExecutor, as_completed
from botocore.config import Config  # Import Config for custom timeouts
 
print("NetGuard Orchestrator started successfully.")
 
# Create a Lambda client with custom timeouts:
lambda_client = boto3.client(
    'lambda',
    config=Config(
        read_timeout=900,     # Wait up to 900 seconds (15 minutes) for a response
        connect_timeout=60    # 60 seconds connection timeout
    )
)
 
# Environment variables: the names (or ARNs) of the three agent Lambdas and the ticket generator
AGENT_1 = os.environ['AGENT_1_FUNCTION_NAME']  # e.g., "NetGuard_Ingestor"
AGENT_2 = os.environ['AGENT_2_FUNCTION_NAME']  # e.g., "NetGuard_Analyzer"
AGENT_3 = os.environ['AGENT_3_FUNCTION_NAME']  # e.g., "NetGuard_Aggregator"
TICKET_GENERATOR = os.environ['TICKET_GENERATOR_FUNCTION_NAME']  # e.g., "NetGuard_TicketGenerator"
 
def lambda_handler(event, context):
    print("[DEBUG] Orchestrator invoked with event:", json.dumps(event, indent=2))
 
    # Step 1: Invoke Agent 1 (Ingestor)
    print(f"[DEBUG] Invoking Agent 1: {AGENT_1}")
    response_agent1 = lambda_client.invoke(
        FunctionName=AGENT_1,
        InvocationType="RequestResponse",  # synchronous call
        Payload=json.dumps(event)           # pass entire event to Agent 1
    )
    # Parse Agent 1's output
    agent1_payload = json.load(response_agent1["Payload"])
    print("[DEBUG] Response from Agent 1 (Ingestor):", agent1_payload)
 
    # Extract chunk keys from Agent 1
    chunk_keys = agent1_payload.get("chunk_keys", [])
    if not chunk_keys:
        print("[ERROR] No chunk keys returned by Agent 1. Exiting pipeline.")
        return {
            "statusCode": 400,
            "message": "No chunks generated by Agent 1 (Ingestor)."
        }
 
    print(f"[DEBUG] Received {len(chunk_keys)} chunk(s) from Agent 1.")
 
    # Step 2: Invoke Agent 2 (Analyzer) concurrently for each chunk
    partial_outputs = []
   
    def invoke_agent2(chunk_key):
        print(f"[DEBUG] Invoking Agent 2: {AGENT_2} for chunk: {chunk_key}")
        analyzer_event = {"chunk_key": chunk_key}
        response = lambda_client.invoke(
            FunctionName=AGENT_2,
            InvocationType="RequestResponse",
            Payload=json.dumps(analyzer_event)
        )
        agent2_payload = json.load(response["Payload"])
        print(f"[DEBUG] Response from Agent 2 for chunk {chunk_key}:", agent2_payload)
        return chunk_key, agent2_payload.get("partial_output_key")
 
    # Use ThreadPoolExecutor to run up to 10 Lambda invocations concurrently
    with ThreadPoolExecutor(max_workers=6) as executor:
        # Create a dictionary mapping Future to chunk_key for error handling
        future_to_chunk = {executor.submit(invoke_agent2, ck): ck for ck in chunk_keys}
        for future in as_completed(future_to_chunk):
            chunk, partial_key = future.result()
            if partial_key:
                partial_outputs.append(partial_key)
            else:
                print(f"[WARN] No partial_output_key for chunk {chunk}")
 
    if not partial_outputs:
        print("[ERROR] Agent 2 produced no partial outputs. Exiting pipeline.")
        return {
            "statusCode": 400,
            "message": "Analyzer produced no partial outputs."
        }
 
    print(f"[DEBUG] Collected {len(partial_outputs)} partial outputs from Agent 2.")
 
    # Step 3: Invoke Agent 3 (Aggregator) to merge partial outputs
    print(f"[DEBUG] Invoking Agent 3: {AGENT_3} to merge partial outputs.")
    aggregator_event = {"partial_keys": partial_outputs}
    response_agent3 = lambda_client.invoke(
        FunctionName=AGENT_3,
        InvocationType="RequestResponse",
        Payload=json.dumps(aggregator_event)
    )
    agent3_payload = json.load(response_agent3["Payload"])
    print("[DEBUG] Response from Agent 3 (Aggregator):", agent3_payload)
    final_output_key = agent3_payload.get("final_output_key")
    if not final_output_key:
        print("[WARN] No final_output_key returned by Agent 3.")
 
    # Step 4: Invoke Ticket Generator to create JIRA tickets
    print(f"[DEBUG] Invoking Ticket Generator: {TICKET_GENERATOR}")
    ticket_event = {"final_output_key": final_output_key}
    response_ticket = lambda_client.invoke(
        FunctionName=TICKET_GENERATOR,
        InvocationType="RequestResponse",
        Payload=json.dumps(ticket_event)
    )
    ticket_payload = json.load(response_ticket["Payload"])
    print("[DEBUG] Response from Ticket Generator:", ticket_payload)
 
    print("[DEBUG] NetGuard pipeline completed successfully.")
    return {
        "statusCode": 200,
        "message": "NetGuard pipeline executed successfully. Final file generated and tickets created.",
        "chunk_keys": chunk_keys,
        "partial_outputs": partial_outputs,
        "final_output_key": final_output_key,
        "ticket_response": ticket_payload
    }
 
 